### ISSUE TITLE
Issue with org/eclipse/microprofile/health/HealthCheckResponse.java

### ISSUE THREAD

**Issue by susanodom** [eclipse/microprofile-health#103]
The assignment in the method below is wrong.

    public static void setResponseProvider(HealthCheckResponseProvider provider) {
        HealthCheckResponse.provider = HealthCheckResponse.provider;
    }
which should be:
    public static void setResponseProvider(HealthCheckResponseProvider provider) {
        HealthCheckResponse.provider = provider;
    }

**Comment by heiko-braun** [comment]
Mind to send  a PR?
