### ISSUE TITLE
Mistake in "Appendix A: REST interface specification" text? - question

### ISSUE THREAD

**Issue by cealsair** [eclipse/microprofile-health#105]
The following section in the documentation:
https://github.com/eclipse/microprofile-health/blob/master/spec/src/main/asciidoc/protocol-wireformat.adoc#appendix-a-rest-interface-specifications
under the "Status Codes:" section, it says:
"
- 500 in the case the consumer wasn't able to process...
"
Is this correct?  Shouldn't it say:
"
- 500 in the case the producer wasn't able to process...
"
instead?

**Comment by heiko-braun** [comment]
Thanks @cealsair, good catch!
