### ISSUE TITLE
Worth saying that checks are unordered? 

### ISSUE THREAD

**Issue by scottkurz** [eclipse/microprofile-health#106]
Relatively new to this, so not sure if this has come up before....  

Thinking it might be worth saying that the checks are unordered (assuming I haven't missed some discussion where there was supposed to be an order;  relatively new to the discussion here).

Given that probably a given implementation will return the same types of checks in the same order, I could imagine if I try hard enough someone building some dependency on the order of checks.  

A specific statement that you shouldn't would make this clear.

**Comment by heiko-braun** [comment]
+1

**Comment by heiko-braun** [comment]
I think this will be superseded by #110 . @scottkurz Thoughts?

**Comment by scottkurz** [comment]
Agree that if we were to proceed with the proposal in #110 then this issue #106 would become obsolete.   

But I don't see that #110 has progressed any since, as noted there, the proposals there seem to either incompatible with the existing format or potentially implementation-specific.    

But maybe that's just repeating the obvious... are you asking what I think about #106?

**Comment by johnament** [comment]
Can checks perhaps be ordered by adding `@Priority` somewhere?  Or perhaps is it OK if checks are actually executed in other threads?

**Comment by scottkurz** [comment]
Well, I was just opening this to more clearly articulate (in the spec wording) the decision that I assumed had been made.    So any other ideas are really separate from my angle here.

**Comment by heiko-braun** [comment]
As @scottkurz said, the initial motivation behind this issues was to clearly point out that checks are not ordered. And I still don't see why they should be. There is a single overall outcome and the order of execution doesn't change anything to it.

**Comment by cescoffier** [comment]
I believe it should be written in the spec, just to be clear.

**Comment by antoinesd** [comment]
We agree to add this statement
