### ISSUE TITLE
Clarify behavior of @RequestScoped beans injected in the context of a Health Check (in the spec and TCK)

### ISSUE THREAD

**Issue by scottkurz** [eclipse/microprofile-health#109]
Not sure if there's been any discussion of this already.

Seems that `@RequestScoped` would be a natural one to support in the future.

Not sure about `@SessionScoped`.   Thoughts? 

As far as `@Dependent`... seems like might as well add a TCK test using this scope though hard to see how there could be any ambiguity or any undiscovered bugs at this point. 

(BTW, I don't see a test using dependent, in spite of the assertion message:  _Expected a dependent CDI bean to be invoked, to resolve the system state_ in **DelegateProcedureSuccessfulTest.java**.  Is that message misleading or am I reading that wrong?)

**Comment by scottkurz** [comment]
Probably the first thing worth clarifying is that Health Check beans execute under a request context scoped to the invocation of the */health* URL (assuming that's what we want).    This way any beans injected into the HC beans with `@RequestScoped` will be scoped accordingly.    

As for the HC bean itself, you probably wouldn't notice the difference between dependent-scoped vs request-scoped when  invoking */health*... you get a new one each time either way.      You only notice if you inject this HC bean into some other part of your app... (which might be odd on the one hand, but I guess why not?).   So allowing `@RequestScoped` just confirms that's OK for a case like that.

**Comment by mkouba** [comment]
#119 is probably related to this issue.

**Comment by antoinesd** [comment]
I don't think we should enforce a given scope for HealthCheck Bean. I can imagine case where user may want to have an application scoped bean and recompute the health in call() method each time or use case where computation is cached in the bean and have it dependent or request scoped. Session Scoped is probably the less useful but I don't see the interest of adding a restriction here.
