### ISSUE TITLE
Unclear on what needs to be provided by impl or app

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-health#11]
It is unclear what is needed to be provided impl or apps. Please can you clarify this. I am blocked by the unresolved question I posted on @heiko-braun 's pr.

**Comment by heiko-braun** [comment]
Some things take time. I am not working on this full time, hence I am asking you to be patient if a response takes longer than expected.

**Comment by Emily-Jiang** [comment]
I understand your situation @heiko-braun, but we have been blocked for some time. We would like to experiment this spec. Also, we would like to contribute and help with moving along faster. Maybe this is microprofile-wide discussion on how to move along faster to remove bottleneck.

**Comment by heiko-braun** [comment]
I would suggest we settle on this: The app provides the health check procedures (impl. of https://github.com/eclipse/microprofile-health/blob/master/api/src/main/java/org/eclipse/microprofile/health/HealthCheckProcedure.java) and the runtime the remainder (http bindings, security, etc)

**Comment by heiko-braun** [comment]
@Emily-Jiang feel free to close this if things became more clear by now.

**Comment by heiko-braun** [comment]
I am assuming that after our call this has become sufficiently clear, hence closing this.
