### ISSUE TITLE
Clarify the official name of the health spec and use it consistently

### ISSUE THREAD

**Issue by OndrejM** [eclipse/microprofile-health#118]
What is the official name of this spec? Is it Health, Health Check, Service Health Check, Healthchecks?

The names isn't consistent across various places:
 - The spec PDF says "Service Health-Checks"
 - The [1.0 release page ](https://github.com/eclipse/microprofile-health/releases/tag/1.0) and the umbrella MP PDF say "Health Check"
 - The README in this repository says "Service Healthchecks"

All the above names should be unified.

**Comment by OndrejM** [comment]
I suggest "Health Check" as it's already in the releases page and also in the MP 1.2 spec

**Comment by antoinesd** [comment]
+1
Full name will be "Microprofile Health Check"
