### ISSUE TITLE
Clarify integration with CDI

### ISSUE THREAD

**Issue by mkouba** [eclipse/microprofile-health#119]
The spec should clarify whether `HealthCheck` procedures are used as **bean instances** (with lifecycle bound to CDI contexts) or **non-contextual instances** (i.e. instances created by CDI SPI but without a well-defined lifecycle). The differences are:

* a bean instance can be injected in other beans and so its state could be easily updated
* a non-contextual instance cannot be injected
* scope annotations are ignored for non-contextual instances - the lifecycle is implementation specific
* non-contextual instances cannot receive CDI event notifications (observers are ignored)

**Comment by scottkurz** [comment]
I would think the intent is clearly to use **bean instances**.  The spec does say:

_Within CDI contexts, beans that implement HealthCheck and annotated with @Health are discovered automatically and ..._

Also there are some TCK beans marked with `@ApplicationScoped`.   Would have to check to see how far the TCK goes to verifying CDI's scoping rules.

Still, clearer wording could only help if we agree on the behavior already.

**Comment by heiko-braun** [comment]
I agree, there is a bit of mishmash here. From my point of view, health check procedures should be a non-contextual instances. As such they can access and delegate to managed bean instances for calculating the state, but I don't see why they would need to be  fully managed themselves.

**Comment by Emily-Jiang** [comment]
As per the comments from @scottkurz , the spec hints the procedure is bean instance. In the readme doc, 
```
@Health
@ApplicationScoped
public class CheckDiskSpace implements HealthCheck {

    public HealthCheckResponse call() {
        [...]
    }
}
```

I think MP Health implementer discovers the healthcheck beans  via CDI and then find out the aggregated view on up/down. It is useful to the runtime. However, end user may not find it useful. The lifecycle does not matter that much. I think the scope for the HealthCheck should be @Dependent as I don't think it makes sense to share an instance.

**Comment by mkouba** [comment]
Both solutions are fine and it really depends on how users will implement health checks.

For bean instances and `@ApplicationScoped` I can imagine a use case similar to this:
````
@Health
@ApplicationScoped
public class CheckDiskSpace implements HealthCheck {

    HealthCheckResponse cachedResponse;
   
    public HealthCheckResponse call() {
      return cachedResponse;
    }
  
   void updateResponse(@Observes UpdateHealthChecks event) {
      cachedResponse = ...
   }

}
````
E.g. allow to update procedures in a decoupled way.

And I think the lifecycle does matter as it's part of the `HealthCheck` API contract.

**Comment by heiko-braun** [comment]
@mkouba Wha would a proper way to declare non-contextual instances?

**Comment by Emily-Jiang** [comment]
Is @Health absolutely required when implementing the HealthCheck interface? What is the real usage of @Health if there is no need to inject HealthCheck into another class. Besides, @Health cannot be solely relied upon as it is not mandatory. Right?

**Comment by mkouba** [comment]
@Emily-Jiang I asked the same question recently https://github.com/eclipse/microprofile-health/issues/74#issuecomment-363799357. But it seems to be mandatory - the current wording requires both implementation of `HeathCheck` annodated with `org.eclipse.microprofile.health.Health`.

**Comment by mkouba** [comment]
@heiko-braun Do you mean in which way to formulate the spec so that it's clear that procedures are non-contextual instances?

**Comment by heiko-braun** [comment]
@mkouba yes, exactly. If we would decide for non-contextual instances, how would we need to change the spec? How are these expressed?

**Comment by antoinesd** [comment]
Non-contextual instance are useful in 2 cases:

1. when you don't own the code and want to have some CDI feature (dependency injection) on your class
2. when you don't want your instance wrapped in a proxy like CDI impl do

Obviously we are not in case 1, so if 2 is not problem why don't we go for a standard CDI bean and bean instance?
Did I miss something?

**Comment by Emily-Jiang** [comment]
Actually, I prefer the standard CDI bean route, as in this way, the implementor can at least use CDI to get hold of HealthCheck beans. It may not be useful to the end users for sure. Since the spec has already done this way, if we then change to non-contexual, this will be a backward incompatible change for no apparent benefit.

**Comment by heiko-braun** [comment]
So, who can summarise the outcome of this discussion? What are we changing and why?

**Comment by mkouba** [comment]
I'll try to summarize the output today.

**Comment by mkouba** [comment]
## Output
We agreed that `HealthCheck` procedures should be used as bean instances (with lifecycle bound to the CDI contexts). Furthermore, `@Health` qualifier seems to be useless.

## Proposed changes
* Change the wording so that any **enabled** bean with a bean type `org.eclipse.microprofile.health.HealthCheck` can be used as a health check procedure
* Deprecate/make optional `@Health` qualifier
* I think it does not make sense to restrict the scope of a health check bean (most of the scopes should work out of the box)

I'll try to send a PR in a couple of days.

**Comment by struberg** [comment]
Btw it might be nitpicking, but the term 'bean instance' means an instance of a class which `extends Bean<T>`.

What all of you most likely mean is a 'Contextual Reference' according to 6.5 of the CDI spec
https://docs.jboss.org/cdi/spec/1.2/cdi-spec.html#contextual_instances_and_references

**Comment by mkouba** [comment]
I disagree, that would be `Bean<>` instance or instance of `Bean<>`  but of course the spec will not use the term "bean instance" at all. I think we can stick with something like: _"any enabled bean with a bean type org.eclipse.microprofile.health.HealthCheck can be used as a health check procedure"_ and  _"Contextual references of health check procedures are invoked by runtime when the outermost protocol entry point receives an inbound request"_ ;-)

**Comment by heiko-braun** [comment]
thanks @mkouba !

**Comment by antoinesd** [comment]
Sent PR #120 with @mkouba proposal

**Comment by derekm** [comment]
The benefit of `@Health` was quickly disabling a check by commenting it out.

Now I add `@Vetoed` instead?

With strict 1.0-compliant behavior, requiring BOTH extension & annotation, commenting out `@Health` to disable a check is probably more obvious to most users than adding `@Vetoed`. (That isn't to say users shouldn't be expected to learn about `@Vetoed`!)

**Comment by derekm** [comment]
@mkouba @antoinesd -- Can this issue be renamed to something that more obviously reflects what is dealt with here, like "Deprecate `@Health` annotation & call all `HealthCheck` impls" or similar?

**Comment by mkouba** [comment]
I don't think we should rename this issue - the main output of this issues is the clarification that health **checks are CDI contextual references**: their lifecycle is managed by a CDI container, health checks can declare observer methods, etc.

WRT disabling a check - as mentioned CDI defines various ways of disabling beans  - `@Vetoed`, empty `@Typed()`, make a bean an unselected `@Alternative`, extensions, etc.

**Comment by derekm** [comment]
PS: In one PR we're changing already-set-in-stone "outcome"/"state" over to "status"/"status" so we can cater to newbie sensibilities or some newly-preferred regional dialect, and in another PR we're demanding that those same newbs become experts at disabling CDI "beans" when they're just tip toeing into CDI with `bean-discovery-mode="all"` in order to try out MicroProfile Health. Let's develop some consistent rational here...

**Comment by derekm** [comment]
PPS: `README.adoc` is now out of sync with `java-api.adoc`
