### ISSUE TITLE
Revisit the message body of health

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-health#125]
In the current health spec, we have 
```
{
  "outcome": "UP",
  "checks": [
    {
      "name": "first-check",
      "state": "UP",
      "data": {
        "key": "foo",
        "foo": "bar"
      }
    },
    {
        "name": "second-check",
        "state": "UP"
    }
  ]
}
```

In the message it says 'outcome'. I think it should be changed to 'status', which is better understood and also match with what Spring says. In this way, in service-mesh platform, it is much easier to be communicated. Thoughts?

**Comment by kenfinnigan** [comment]
Not sure I agree that `status` is more understood than `outcome`, but if there's desire to change it then I'd say change it to something like `overall-status` or something else that indicates it's a rollup situation.

Also, not sure how Service Mesh plays into this, can you elaborate?

**Comment by seabaylea** [comment]
I think its desirable to users to have a consistent payload across all of their microservices - regardless of the framework (or language) that each is built in.

There isn't a significant level of consistency in the way of convention today, but certainly the most common approach is to use `status` for the overall result.

**Comment by Emily-Jiang** [comment]
@cescoffier further to our discussion at EclipseCon, it is a cool thing that we can sync up in different tools and languages.

**Comment by Ladicek** [comment]
If there's a consensus to rename `outcome` to `status` (and I personally don't find the arguments about consistency very convincing), would it make sense to rename `state` of the individual checks to `status` as well?

**Comment by Emily-Jiang** [comment]
Maybe renaming `state` in the individual to `status` is even better. The top level status is the aggregation of the 2nd level of status.

**Comment by cescoffier** [comment]
+1 to have `status` everywhere.

I would like to discuss the backward compatibility, as it's a breaking change. Application analysing the content of the response would need to update to the new format. We can mark in the spec the `outcome` and `state` as deprecated in the spec. The implementations can decide to provide both for now or drop the old ones. WDYT?

**Comment by cescoffier** [comment]
Another point, should we add a `version` field defining the version of the model?

**Comment by pilhuhn** [comment]
If we add more fields, then it could also be good to optionally allow hints for operations folks, like a short description and a url to more information.

**Comment by cescoffier** [comment]
@pilhuhn for each procedure? or in the global report?

**Comment by pilhuhn** [comment]
I would do it for each procedure and the global report. In many cases we will only see the global report, but if there are many procedures then it is expected that those parts can fail independently and thus the hints would be needed for each of the individual parts that can fail.

**Comment by cescoffier** [comment]
I've opened a first PR doing the renaming: https://github.com/eclipse/microprofile-health/pull/126.

**Comment by cescoffier** [comment]
@pilhuhn the PR mentioned in my previous comment does not include extra-metadata. I would prefer having a second PR extending the model with them. Would you be ok with this?

**Comment by pilhuhn** [comment]
On 21 Jun 2018, at 14:55, Clement Escoffier wrote:

> extending the model with them. Would you be ok with this?

Yes of course

**Comment by cescoffier** [comment]
Updated PR: https://github.com/eclipse/microprofile-health/pull/127

**Comment by Emily-Jiang** [comment]
@cescoffier pleas also update the readme doc accordingly.

**Comment by cescoffier** [comment]
@Emily-Jiang I've updated the README, did I miss something?

**Comment by Emily-Jiang** [comment]
Thank you @cescoffier ! Looks good.

**Comment by derekm** [comment]
Can we rename this issue to "Rename outcome/state to status/status" or similar, so that it is obvious what this issue deals with?

Can we also revert this breaking change and continue this discussion until Health 2.0 is being considered?

I think service meshes should be app framework aware and should talk to each app in it's own way, whether Spring, MicroProfile, Dropwizard, Play, or home-brew stackoverflow copy/paste job.

Service meshes that aren't ping/health service style aware aren't good reasons to impose changes that break service meshes in Health 1.1!

Thanks for reconsidering this change!

**Comment by derekm** [comment]
If MP Health 2.0 is being developed in the `master` branch now, then instead of renaming this ticket, can we reopen this ticket to track all of the changes to the message body?

We're obviously not done revisiting the message body of health.

I'd like to get #110 added in for 2.0.

I'd also like to recommend working with <https://github.com/inadarei/rfc-healthcheck/issues/24>.
