### ISSUE TITLE
Create TCK for liveness and readiness

### ISSUE THREAD

**Issue by antoinesd** [eclipse/microprofile-health#145]

**Comment by antoinesd** [comment]
Most important is the HTTP status code

**Comment by derekm** [comment]
Given the HTTP status code behavior, existing `@Health` checks cannot be assumed to be `@Liveness` checks. I might be able to continue serving requests in a degraded fashion.

I have several systems that can survive and recover from outages using MP Fault Tolerance and batching postponed work into audit logs, so my `@Health` checks there should not automatically become `@Liveness` checks.

**Comment by antoinesd** [comment]
solved with pr #165
