### ISSUE TITLE
Don't deprecate the `@Health` annotation

### ISSUE THREAD

**Issue by derekm** [eclipse/microprofile-health#148]
With strict 1.0-compliant behavior, the benefit of the `@Health` annotation is a quick & obvious way to disable health checks.

Keeping `@Health` also provides a place for group names to be defined as in issue #81 about executing health check groups or individual checks.

MicroProfile Health implementations will from now on forever reference the `@Health` annotation, so why get rid of it so quickly?

Forgive me for saying this, but a lot of activity in MP Health's `master` branch seems to be microscopic nitpicking, second-guessing and flip-flopping, instead of big picture, move-the-ball-down-the-court kind of stuff.

The ship has already sailed with MicroProfile Health 1.0. Implementations will now forever refer to an annotation that is instantly deprecated, which seems wasteful.

**Comment by derekm** [comment]
The introduction of `@Readiness` and `@Liveness` annotations in some sense demands keeping the `@Health` annotation.

See my comment with rationale here on the liveness/readiness PR: https://github.com/eclipse/microprofile-health/pull/142#discussion_r226333188

**Comment by mkouba** [comment]
> With strict 1.0-compliant behavior, the benefit of the `@Health` annotation is a quick & obvious way to disable health checks.

There is a "quick and obvious" way of disabling beans in CDI - `@Vetoed`. See also http://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#what_classes_are_beans.

> Keeping `@Health` also provides a place for group names to be defined...

I believe it should be a dedicated qualifier with a meaningful name.

**Comment by antoinesd** [comment]
out of date
