### ISSUE TITLE
Publish spec & Javadoc at downloads.eclipse.org

### ISSUE THREAD

**Issue by anthonyvdotbe** [eclipse/microprofile-health#158]
MicroProfile Health is the only MicroProfile specification which doesn't publish its artifacts at http://download.eclipse.org/microprofile/
This is particularly useful for the Javadocs, e.g. http://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.0/apidocs/

It would be great if MicroProfile Health would also publish the artifacts of all releases to date there.

**Comment by antoinesd** [comment]
Will do

**Comment by antoinesd** [comment]
done
