### ISSUE TITLE
MP-HC 1.0 response schema does not validate

### ISSUE THREAD

**Issue by starksm64** [eclipse/microprofile-health#160]
Validation of the 1.0 response schema in a tool like https://www.jsonschemavalidator.net/ produces the following error:

> Invalid JSON schema type: string|boolean|int. Path 'properties.checks.items.properties.data.properties.value.type', line 26, position 43.

Looking at the schema validation document, the correct value for the 'properties.checks.items.properties.data.properties.value.type' should be an array of JSON types, leading to this schema which does validate:

```json
{
 "$schema": "http://json-schema.org/draft-04/schema#",
 "type": "object",
 "properties": {
   "status": {
     "type": "string"
   },
   "checks": {
     "type": "array",
     "items": {
       "type": "object",
       "properties": {
         "name": {
           "type": "string"
         },
         "status": {
           "type": "string"
         },
         "data": {
           "type": "object",
           "properties": {
             "key": {
               "type": "string"
             },
             "value": {
               "type": ["string", "boolean", "number"]
             }
           }
         }
       },
       "required": [
         "name",
         "status"
         ]
     }
   }
 },
 "required": [
   "status",
   "checks"
 ]
}
```

**Comment by starksm64** [comment]
Looking further into the json schema syntax, it would seem that we should have a more well defined schema value for the data object as the current definition essentially allows anything since the default value of the additionalProperties schema element not used is true. In the spec we show responses that include properties other than "key" and "value" in the spec:

```json
{
  "status": "DOWN",
  "checks": [
    {
      "name": "firstCheck",
      "status": "DOWN",
      "data": {
        "key": "value",
        "foo": "bar"
      }
    },
    {
      "name": "secondCheck",
      "status": "UP"
    }
  ]
}
```

What if the data schema element was something more like:

```json
...
         "data": {
           "type": "object",
          "patternProperties": {
            "key[a-zA-Z_]*": { "type": "string" },
            "value[a-zA-Z_]*": { "type": ["string", "boolean", "number"] }
          },
           additionalProperties: false
         }
```

**Comment by xstefank** [comment]
@starksm64 agreed, both of your points should be adjusted
