### ISSUE TITLE
Reactive back-pressure health:  /health/back-pressure

### ISSUE THREAD

**Issue by hutchig** [eclipse/microprofile-health#179]
When writing reactive applications one is frequently faced with a situation
where one has a stream that is not flowing as well as expected. 

For situations where two application components are talking to each other across
a reactive interface that implements reactive backpressure. One is fequently not sure
if the sender of data is blocked or not providing data fast enough or if it is being slowed
by reactive back pressure from the receiver not providing request(N) 'tickets' fast
enough.

A similar problem is that we have traditionally used metrics like CPU % or
real memory utilisation as stimulants to scaling up the instances of a
microservice. If a microservice is using reactive back-pressure to prevent
it from getting too 'sweaty', this lack of stress will prevent some of the
traditional symptoms used to trigger the launching of new services.

Both sides of a reactive connection are aware of who has got the
request(N) 'tickets' and how many are outstanding for a particular
client.  Whether ticket 'starvation' is present between two microservices
is an interesting aspect of a running service's health. 

Obviously, this is early warning radar as only some MicroProfile
servers have server to server back pressure but I thought I would
raise it to stimulate thought and as a placeholder for discussion.

**Comment by hutchig** [comment]
It may be that MicroProfile Reactive Messaging could be pulled in to provide
the data required for this in some future release as it handles the
reactive back-pressure and ticketing automatically on behalf of
`@Incoming` and `@Outgoing` annotated methods.  ( @cescoffier ) 
so it aware of tickets (or lack of them).

**Comment by cescoffier** [comment]
As the endpoints provided by the health specification are mostly about indicating a very bad state triggering a reboot; I believe that what you are suggesting is more metrics related.

**Comment by hutchig** [comment]
I think liveness triggers a reboot, but
readyness is the concept of being able to accept traffic.
Perhaps if we work the 'metrics for reactive messaging issue' a little it
will make it clearer.
Generically, I could get that 'health' is the metrics when there are no metrics.

**Comment by donbourne** [comment]
If the reactive messaging manages `@Outgoing` requests, I would think you could instrument that to provide a metric showing the amount of time spent waiting for the "green light" to send more requests.  That would help solve the question of whether the sender or receiver was the cause of requests moving slowly.

**Comment by hutchig** [comment]
That is certainly true Don. If a server was too slow, or not switching on the ‘green light’ at all how would this get to a dashboard or service manager? The upstream services backing up is a symptom not a cause and requests that do get a ticket run fine and fast.

**Comment by hutchig** [comment]
Now I have read round this, I think this is probably a use case for horizontal pod autoscaling with custom metrics rather than a health endpoint 
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

**Comment by donbourne** [comment]
I think it would be useful to define the metrics you need for the HPA as part of the reactive work.
