### ISSUE TITLE
Support for Out-of-Box health procedures from producers

### ISSUE THREAD

**Issue by pgunapal** [eclipse/microprofile-health#180]
From the Protocol and Wireformat document for the Microprofile Health 2.0 spec, it states the following:
`A producer SHOULD support reasonable out-of-the-box procedures`

This indicates that the producers should be able to add their own procedures, that are not part of the application (implementation of the HealthCheck interface), where these out-of-the-box health check responses will be part of the JSON payload, when the individual endpoints are accessed.

However, from the TCK, there are tests that test for the size of the checks, which will not include these out-of-the-box procedures that will be present. 

For example, producers might include an out-of-the-box check to see if the application is started or not in the server for the readiness check, however this extra check will fail most of the TCKs, since the total number of expected checks is different now.

**Comment by xstefank** [comment]
This is a fair point. I would say this shouldn't be hard to fix in TCK. We can just add a config property that will configure the number of out-of-the-box procedures and add it to each size check. Another option is to require that out-of-the-box procedures can be disabled in the implementation (again by config property) and require that TCK is always run with this property set to true. WDYT?

**Comment by donbourne** [comment]
_Another option is to require that out-of-the-box procedures can be disabled in the implementation (again by config property) and require that TCK is always run with this property set to true_

...to me, this approach seems better as it allows for servers that may have different numbers of OOB checks depending on other configuration -- all of which could be disabled for running the TCK

**Comment by pgunapal** [comment]
+1, to adding a config property to disable the out-of-the-box procedures in the implementation, and run the TCK with the property set to true.

As Don mentioned, it will be easier to set it in the implementation side, as there may be different number of OOB checks, for each implementation.

**Comment by Emily-Jiang** [comment]
I disagree with adding property to work about the tck. We need to update tck to make it more flexible.

**Comment by antoinesd** [comment]
I think Idea is more adding a config property to disable all procedure define in vendor implementation and only keep procedures defined by user.

**Comment by kenfinnigan** [comment]
That's my understanding as well.

Disable implementation specific procedures to not impact TCKs expectations

**Comment by xstefank** [comment]
+1 on adding a config property to disable vendor procedures
