### ISSUE TITLE
Make health semantics & usage more compatible with orchestration environments

### ISSUE THREAD

**Issue by sdaschner** [eclipse/microprofile-health#182]
One thing that makes MP Health doesn't work well with orchestration frameworks such as Kubernetes is the fact that there's no straightforward way to define a reliable readiness probe for single applications:

If we go the straightforward way to define a `@Readiness` check (e.g. with the default app-name), we can't reliably use the endpoint `/health/ready` for the Kubernetes readiness probe, since that will, for a short amount of time respond with `HTTP 200` and an empty response: `{"checks":[],"status":"UP"}`.
This pretty much defeats the purpose of the automatic checks, since, in order to be reliable, we have to change the Kubernetes probe from the default HTTP check to a custom check alà `exec: curl ... | grep <app-name>`.

IMO, one of all of the following would make MP Health suitable for real-world applications:

- Defining way to ask for all / a specific check in the URL path (e.g. using `/health/<check-name>` to query for the specific check that defaults to `HTTP 5xx` or `HTTP 404` if not successful (yet))
- Using (the default EE way) the deployed context name of the application (e.g. using `/health/<app-name>` that defaults to `HTTP 200` once _app-name_ is deployed.)
- In general, requiring some default way to check the straightforward way of liveness (server/runtime available?) and readiness (application successfully started/deployed?) without requiring some code in the app deployment artifact

This might be related to #45.

Right now, for most applications, there is little value added in MP Health over doing a simple JAX-RS resource for `@Path("health")` that responds with OK. This will be `HTTP 200` as soon as the app is successfully deployed, and that's it. So, TBH, I see little value in plain MP Health as is, for a lot of enterprise projects.

**Comment by kenfinnigan** [comment]
> If we go the straightforward way to define a `@Readiness` check (e.g. with the default app-name), we can't reliably use the endpoint `/health/ready` for the Kubernetes readiness probe, since that will, for a short amount of time respond with `HTTP 200` and an empty response: `{"checks":[],"status":"UP"}`.

Can you clarify what is happening to make it respond with `HTTP 200` for a period?

**Comment by sdaschner** [comment]
Sure:

```
$> while true; do curl .../health/ready; ...; done

curl: (56) Recv failure: Connection reset by peer
curl: (56) Recv failure: Connection reset by peer
...
HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
...
HTTP/1.1 200 OK
{"checks":[],"status":"UP"}

# 200 OK but app is not ready yet

...
HTTP/1.1 200 OK
{"checks":[{"data":{},"name":"myapp","status":"UP"}],"status":"UP"}

# only now it's actually ready
```

**Comment by kenfinnigan** [comment]
So it's a problem of the Health implementation not knowing there's a `@Readiness` check to perform and returning `UP` before the check is found?

It sounds like it's an implementation bug that individual health checks are not available at the time an initial health check is requested

**Comment by sdaschner** [comment]
> So it's a problem of the Health implementation not knowing there's a @Readiness check to perform and returning UP before the check is found?

Yep, correct.

Is there something in the spec that requires the initial health check to fail until all health checks are a) resolved and b) succeed?

In any way if would greatly help the predictability of the checks if they could be performed against specific check / app names.

**Comment by kenfinnigan** [comment]
Not sure if there's wording to that effect, but that does seem to be the easiest change to make.

At least then an implementation knows it needs to fail until there's at least one of the defined health checks passing.

Another option for this, which I think was mentioned somewhere previously, is the idea of defining a list of "required" checks that must pass to consider the service UP.

**Comment by sdaschner** [comment]
I agree, so at least if it's possible for the runtime ( / application server) to know about certain health check at start time already, then it should (in the future) respond with failed checks until all of them pass.

I do see an issue with more traditional runtimes that, at least theoretically, support deploying multiple applications, and support that while running. I. e. if we're deploying a new WAR with _my-app_, there's no easy way to query the ready state of that app without "parsing" (or grep-ing) the check response for the _my-app_ string name... Requesting specifics checks in the URL (e.g. `/health/my-app/`) would help a lot here.

**Comment by donbourne** [comment]
If `/health/ready` were to return DOWN until an app is ready to serve traffic, or even return a 404 until that time, and if the app being up implied that the readiness checks needed to be in place, I think that would cover this startup time issue.  

I'm somewhat not in favor of having a pre-defined list of checks as that would be difficult for servers that can deploy new apps after startup.

**Comment by sdaschner** [comment]
> If `/health/ready` were to return DOWN until an app is ready to serve traffic, or even return a 404 until that time, and if the app being up implied that the readiness checks needed to be in place, I think that would cover this startup time issue.

Yes, agree. Implies that only a single app runs on the runtime, which, from my experience, matches pretty much all modern projects.

**Comment by donbourne** [comment]
The 404 approach is what we're using in OpenLiberty (mpHealth-2.0) as it somewhat avoids the question of what state should be returned for health before the app is up.

**Comment by xstefank** [comment]
isn't this already covered in https://github.com/eclipse/microprofile-health/blob/master/spec/src/main/asciidoc/protocol-wireformat.adoc#health-check-procedures

**Comment by sdaschner** [comment]
@donbourne Well, my output showing first an empty response and only then the successful check was tested with Open Liberty `19.0.0.7/wlp-1.0.30.cl190720190623-0300 on OpenJ9, version 12.0.1+12` and feature `mpHealth-2.0`. Happy to open up an issue in the OL repo, if that is currently not desired.

@xstefank I would say so to, however, for the case of a traditional runtime that supports multiple deployments, the (philosophical) question is whether an app that isn't deployed yet counts towards expected checks, as in sentence.

> A producer with no health check procedures expected or installed MUST return positive overall status (i.e. HTTP 200)

However, I believe we should make the spec more clear and stricter on that topic, otherwise it defeats the purpose of the checks, IMO.

**Comment by xstefank** [comment]
@sdaschner multi deployment applications are still an open question for all specs:
- https://github.com/eclipse/microprofile-health/issues/45
- https://groups.google.com/forum/?hl=en#!topic/microprofile/yF7sJqU2hNQ

I will try to bring this up again in the community. However, generally MicroProfile was designed for microservices thus single deployment per runtime which you've said is actually the case in most modern apps today.

**Comment by fmhwong** [comment]
@sdaschner We made a change in Open Liberty last week to return 503 where apps are not yet started.  Can you test again with the latest driver?  If it is still not working, please open an issue in https://github.com/OpenLiberty/open-liberty/issues.

**Comment by sdaschner** [comment]
Thanks @fmhwong.

Again, in general, do you all see a need to change the wording in the specification document? For me it didn't read like it strictly requires the impl to return failed until all apps have been started, all checks have been resolved, _and_ the checks are successful.

Only tested with Liberty so far; if you claim this was specific to Liberty, I'm happy to close this.

**Comment by donbourne** [comment]
I think it would be helpful if the spec doc could say what should happen in the case where the /health endpoints are accessible before the application (or applications) are accessible.  Currently it's left to the implementer as I'm not sure this case was envisioned when the spec was written.

**Comment by kenfinnigan** [comment]
Doesn't the specification define that if the endpoint is available but the application(s) is not, then it should return a state of down?

Irrespective of whether we're talking traditional app servers or microservices. It's up to the implementation in a traditional app server to ensure it returns DOWN when there is an application not ready.

I'm not sure what isn't clear

**Comment by donbourne** [comment]
In the "Health Check Procedures" section (p. 20 of the 2.0.1 version of the spec) it says:

- A producer MUST support custom, application level health check procedures
- A producer SHOULD support reasonable out-of-the-box procedures
- A producer with no health check procedures expected or installed MUST return positive overall status (i.e. HTTP 200)
- A producer with health check procedures expected but not yet installed MUST return negative overall status (i.e. HTTP 503)

I don't think that clearly covers what to do if my app initialization hasn't progressed to the point at which I know what health checks are "expected".
I think it may also be glossing over the difference between liveness and readiness.

Before I suggest any alternate wording, I thought I'd try to state in pseudocode what I think we're aiming for:

```
if (scan for liveness checks not complete or any liveness checks are not ready to run)
    return overall liveness status according to return result of liveness checks that are ready to run
    return overall readiness status 503

else if (scan for readiness checks not complete or any readiness checks are not ready to run)
    return overall liveness according to return result of liveness checks
    return overall readiness status 503

else 
    return overall liveness according to return result of liveness checks
    return overall readiness according to return result of liveness checks
```

Does that look right?

**Comment by kenfinnigan** [comment]
Can you clarify what is meant by `scan for liveness checks not complete`?

**Comment by donbourne** [comment]
`scan for liveness checks not complete` just means I haven't opened/read through the app(s) to discover whether it has liveness checks yet.

**Comment by kenfinnigan** [comment]
Ok.

So you're suggesting an adjustment to the fourth bullet, in particular around "health check procedures expected"?

Depending on the wording I think that would be ok. My concern is if we start adding language that clearly applies to runtimes with multiple deployments vs a runtime with a single application

**Comment by donbourne** [comment]
yes, probably to the 3rd and 4th bullets.  I'll draft something in a PR that tries to avoid the word "application" :-)

**Comment by xstefank** [comment]
I believe this was covered in https://github.com/eclipse/microprofile-health/pull/256 so I'm closing this but please feel free to reopen.
