### ISSUE TITLE
Add convenience methods for creating health check responses

### ISSUE THREAD

**Issue by sdaschner** [eclipse/microprofile-health#184]
From my experience, defining health check responses very often results in creating successful (or failed) named responses for a check.
To make using the API easier we should define default methods for the following:

```java
HealthCheckResponse.up("check-name");
// equivalent to HealthCheckResponse.named("check-name").up().build();

HealthCheckResponse.down("check-name");
// equivalent to HealthCheckResponse.named("check-name").down().build();
```

Method signatures just a suggestion, of course.

**Comment by xstefank** [comment]
+1, good idea
