### ISSUE TITLE
2.0 TCK failed with wrong URI

### ISSUE THREAD

**Issue by fmhwong** [eclipse/microprofile-health#185]
We followed https://github.com/eclipse/microprofile-health/blob/master/tck/running_the_tck.asciidoc and created our own `URIProvider` class.

When running 2.0 TCK, Arquillian injected application root to `URI`.  As a result, the health endpoint became `http://host:port/tck//health`.  All tests that accessing the health endpoint failed with 404.

https://github.com/eclipse/microprofile-health/blob/fc7010a2a13ced148a4af8b0832fb40af0f40be7/tck/src/main/java/org/eclipse/microprofile/health/tck/TCKBase.java#L53

We ran the tests 10 times and the tests failed 4 out of 10 times.  It looks like the default app URI injection was racing with our own URIProvider.

**Comment by xstefank** [comment]
This seems to be an issue with your Arquillian settings. I just tried with [SmallRye implementation](https://github.com/smallrye/smallrye-health) doing just `mvn clean install` and the TCK ran without issues.

**Comment by fmhwong** [comment]
Currently, we use `ExtensionBuilder.service()` to register our own `ResourceProvider`.  I am trying to use `ExtensionBuilder.override()` to override Arquillian's `URIResourceProvider` and see if this solves the problem.

**Comment by xstefank** [comment]
I wish I could help more but without seeing the code it's hard :) However, do you still think that it is an issue on the TCK side?

**Comment by fmhwong** [comment]
I got it to work by extending `URIResourceProvider`.  The example `URIProvider` class in https://github.com/eclipse/microprofile-health/blob/master/tck/running_the_tck.asciidoc will cause nondeterministic result.  If `URIResourceProvider` is loaded first, the test will fail.  If `URIProvider` is loaded first, the test will pass.

**Comment by xstefank** [comment]
Do you fancy contributing your findings to that document, please?
