### ISSUE TITLE
web contexts are implementation specific and need to be adapted for test runs

### ISSUE THREAD

**Issue by heiko-braun** [eclipse/microprofile-health#19]

**Comment by heiko-braun** [comment]
The deployments used by the TCK to verify the implementation are use runtime  (implementation) specific web contexts. I.e we cannot assume that each runtime provides a `HOST:PORT/health` HTTP binding. In some cases it may be `HOST:PORT/APP_CONTEXT/health`. 

To support these cases the TCK would need to provide a test adapter, that allows to adjust the web context for testing if needed. I would suggest we introduce a `TestProperties` that's loaded through a service loader. This would allow each runtime to provide a custom `TestProperties` for access to arbitrary custom properties where needed or useful.

**Comment by heiko-braun** [comment]
We might be using the microprofile config api to provide the customisation of test runs

**Comment by jmesnil** [comment]
#33 is a proposal to make the health URL configurable using a System property by the implementations running the TCK

**Comment by jmesnil** [comment]
(Using the MicroProfile Config API is a better solution that should be postponed after the release of MicroProfile 1.1 and Config 1.0)

**Comment by heiko-braun** [comment]
#33 works for me . Thanks @jmesnil
