### ISSUE TITLE
Check dependencies  for security and have up to date reps

### ISSUE THREAD

**Issue by antoinesd** [eclipse/microprofile-health#196]

**Comment by pgunapal** [comment]
Similar Issue for mpMetrics:
https://github.com/eclipse/microprofile-metrics/issues/284

Need to verify if we have the same security issues for mpHealth.

**Comment by xstefank** [comment]
@antoinesd or any other committer, do you see the Security tab in this repository? This should list the vulnerabilities GitHub knows of.

**Comment by antoinesd** [comment]
The security tab is empty. I think it's safe to close this issue
