### ISSUE TITLE
Unauthenticated health check payload

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-health#2]
For unauthenticated users, what should be in the payload? Spring boot has this policy on HTTP health endpoint format and access restrictions. It sounds reasonable to me. Do we need to follow the similar approach or doing something different? We need to spec this.

**Comment by jmesnil** [comment]
I think you are referring to https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-monitoring.html#production-ready-health-access-restrictions

This sounds reasonable. I'd propose that the spec states that:
* The HTTP health endpoint SHOULD be accessible for unauthenticated users
* The producer SHOULD discard any data from the payload (leaving only the global outcome) for unauthenticated users
* The producer SHOULD discard any data from the payload for authenticated users if they have not enough privilege/permissions to read such data

**Comment by heiko-braun** [comment]
Maybe we should carry over the protocol spec document so we can PR it here?

**Comment by Emily-Jiang** [comment]
@jmesnil yes. @heiko-braun can you bring over the protocol spec to this repo?

**Comment by heiko-braun** [comment]
@Emily-Jiang The protocol spec resides in spec/protocol-wireformat.adoc 

@jmesnil Feel free to submit a PR including the proposed changes above

**Comment by heiko-braun** [comment]
I am going to add to @jmesnil lists:

- Unauthenticated requests should have no payload, but leave the status mapping intact

And going to drop: 

- The producer SHOULD discard any data from the payload for authenticated users if they have not enough privilege/permissions to read such data

Introducing authz priviledges is too complex IMO.

**Comment by heiko-braun** [comment]
Carried over from #47:

> For reference, Spring supports authentication for the health check endpoints generated by their actuators. As noted, it acts as a filter on the returned payload (it has no bearing on which checks are executed). Unauthenticated requests get the sparest of answers {"status":"UP"} or {"status":"DOWN"}. You only get the details if you're logged in. To me, that is the difference between use by automation (up/down) and use by a human (what exactly is going on with this server...).

**Comment by antoinesd** [comment]
This feature belong to a broader scope. Idealy it should addressed by an MP "umbrella" spec

**Comment by Emily-Jiang** [comment]
Why does this one closed without any resolution?
