### ISSUE TITLE
Create Eclipse CQ (contribution questionnaire) for new dependencies

### ISSUE THREAD

**Issue by antoinesd** [eclipse/microprofile-health#200]
PR #197 added new dependencies.
We should create CQs in IPzilla for these

**Comment by antoinesd** [comment]
According to MP 3rd party dependencies process:  https://wiki.eclipse.org/MicroProfile/3rdPartyDependencyProcess
`com.github.java-json-tools:json-schema-validator` should be listed in CQ

**Comment by antoinesd** [comment]
CQ created: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20779

**Comment by xstefank** [comment]
@antoinesd thanks!

**Comment by antoinesd** [comment]
CQ is resolved
