### ISSUE TITLE
Health Group introduced caused more confusion rather than helping

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-health#232]
I reviewed the newly released MP Health 2.2. I am confused about the use case of introducing HealthGroup. What use case is this about? I think it introduces more confusion rather than helping much.
For k8s, we have /heath/live and /health/ready, which are good enough.
For this health group, k8s operation team has no clue which endpoint the groups will belong to. With these extra annotations/endpoints, it is confusing for no obvious reasons.

**Comment by xstefank** [comment]
@Emily-Jiang The original issue is #81 which was a request from the community.

**Comment by antoinesd** [comment]
Sorry @Emily-Jiang, I really don't get what is confusing in this very straightforward feature. I also answered in the group

**Comment by antoinesd** [comment]
Ok, after group discussion, we decided to revert `@HealthGroup`  for 2.2 and continue discussion in #81 for 3.0
