### ISSUE TITLE
Snapshots build fail on baseline plugin

### ISSUE THREAD

**Issue by xstefank** [eclipse/microprofile-health#234]
The snapshots have been failing for several days: https://ci.eclipse.org/microprofile/view/Health/job/Health-maven-snapshots/

The error is:

06:46:17 [INFO] The baseline version was found to be 2.2-RC1
06:46:18 [ERROR] The bundle version change (2.2.0 to 2.2.0) is too low, the new version must be at least 2.2.1

I believe that we should set the version to 2.3-SNAPSHOT if I'm not mistaken. @Emily-Jiang can you confirm, please?

**Comment by antoinesd** [comment]
I agree it's probably the origin of this issue

**Comment by Emily-Jiang** [comment]
The build is now back to normal with the reset of the baseline.

**Comment by antoinesd** [comment]
Thx @Emily-Jiang. Issue was resolved with #237 resolution
