### ISSUE TITLE
Missing a Health 2.2 release plan

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-health#242]
Missing in [release list](https://projects.eclipse.org/projects/technology.microprofile/governance). Please create a release plan. You can look at others (metrics, fault tolerance, etc) to get an idea of what to enter. "Create a release" is in the committer tools list.

**Comment by xstefank** [comment]
So sorry @jclingan I didn't get to it sooner. Thanks for the remainder.

Here it is - https://projects.eclipse.org/projects/technology.microprofile/releases/health-2.2
