### ISSUE TITLE
Add release note to document MP Health 3.0

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-health#262]
In MP Health 3.0, there are backward incompatible changes. All of the changes need to be mentioned in Release note.

**Comment by xstefank** [comment]
Hi @Emily-Jiang thanks for the heads up. We're tracking breaking changes with this label - https://github.com/eclipse/microprofile-health/issues?q=is%3Aissue+label%3Abreaking_change+. We will mention them in release notes.

**Comment by antoinesd** [comment]
Hi @Emily-Jiang every version of MP Health spec has a [release notes section](https://download.eclipse.org/microprofile/microprofile-health-2.2/microprofile-health-spec.html#release_notes_2). So there is no reason to assume that we wouldn't add one to the next release.

**Comment by xstefank** [comment]
I'll close this as this will be included in the release notes.
