### ISSUE TITLE
Startup probe type not supported

### ISSUE THREAD

**Issue by ChetHosey** [eclipse/microprofile-health#274]
K8s 1.16 added a third type of probe, the Startup probe. This API only provides for Readiness and Liveness.

At first pass Startup looks just Liveness with different thresholds. However an app might want these to differ. For example an app may want the init probe to fail if a JDBC connection is unavailable (in case of a configuration error), but allow liveness checks to pass after startup (to avoid cascading failures in the event of a database outage).

**Comment by xstefank** [comment]
Thanks for the report. This will be included in 3.1.
