### ISSUE TITLE
Health check endpoint should have app name

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-health#29]
As I mentioned in one previous PR, I would like the health endpoint to be the suffix of the app name, as there might be multiple apps deployed in a server.

**Comment by jmesnil** [comment]
Having a single health endpoint is good to check the overall healthiness of a server (producer in the spec).
However it SHOULD also be possible to check the healthiness of deployments (that could be considered as components of the producer).

The spec should allow to provide further inspection through the heatlh endpoint to check healthiness of a given component.
* /health would check the global healthiness
* /health/<component> would check the healthiness of the component (through its associated health check procedures).

An app server could then provide different URLS for:
* /health
* /health/<deployment name> -> queries the health check procedures of the deployment
* /health/server -> queries the health check procedures of the app server itself

This has the advantage of keeping the deployment endpoint space clean.
We could also ensure that a call to `/health` optionally returns a list of links for every available subcomponents.

What do you think?

**Comment by heiko-braun** [comment]
I've carried over the comments to  #45 and will close this one as a duplicate issue.
