### ISSUE TITLE
Add TCK for HealthChecks produced with CDI method producers for Startup

### ISSUE THREAD

**Issue by xstefank** [eclipse/microprofile-health#293]
@Emily-Jiang correctly pointed in https://github.com/eclipse/microprofile-health/pull/292#discussion_r636011181 that we don't have TCK for other than class level HealthChecks for Startup health checks. We should add some tests for at least CDI method producers as field and parameter injections (Qualifier targets) are more targeted towards use mostly in the implementations.

**Comment by pgunapal** [comment]
We do have a TCK test case called [CDIProducedProceduresTest](https://github.com/eclipse/microprofile-health/blob/master/tck/src/main/java/org/eclipse/microprofile/health/tck/CDIProducedProceduresTest.java), which 
verifies the liveness and readiness health integration with CDI when the Health Check procedures are defined with * CDI Producers. The test uses the following [CDIProducedProcedureCheck](https://github.com/eclipse/microprofile-health/blob/master/tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/CDIProducedProcedureCheck.java) as a deployment test, which adds the `@Liveness` and `@Readiness` HealthChecks  with CDI method producers. We probably need to update the test case and deployment to verify the `Startup` health integration with CDI as well.
