### ISSUE TITLE
Failed health checks returning 503 instead of 500

### ISSUE THREAD

**Issue by nderwin** [eclipse/microprofile-health#314]
While investigating https://github.com/smallrye/smallrye-health/issues/161, and comparing to the spec (https://github.com/eclipse/microprofile-health/blob/master/spec/src/main/asciidoc/protocol-wireformat.asciidoc#status-codes), it looks like if a (runtime) exception is thrown from a health check method, eventually the response should be a status of 500 instead of 503.  In order to facilitate that, it also looks like a new enum value is needed for the status to represent the "undetermined" state. 

There are already TCK tests throwing exceptions out of the health checks, but they are validating a response status of 503.

**Comment by xstefank** [comment]
@nderwin yes, that test is specific to SR. Please see my response in the SR issue. I believe we shouldn't kill the application if health checks throw exceptions. But @pgunapal how do you handle it in OL please?

**Comment by xstefank** [comment]
Yes, so I guess that example was written by the same person that implemented this in SR. So I think we should be returning 503 if we can catch the exception to stay aligned with our 200/503 response. 500 will be reserved for generic errors that cannot be processed by the implementation, e.g. OOME. I believe that in such cases HTTP server generally responds with 500 (internal server error).

**Comment by nderwin** [comment]
@xstefank Alright, I'll go ahead and close this one, however, the spec might need a little more clarification to note that the documented 500 response is not intended to be produced by an MP implementation, rather it's a consequence of the application being health checked being not available to serve any meaningful response.
