### ISSUE TITLE
microprofile-health-3.1  build failed on baseline plugin 

### ISSUE THREAD

**Issue by saumya1singh** [eclipse/microprofile-health#318]
The build is failing with this error 
I saw this plugin is not directly used in 3.1 microprofile-health.

[ERROR] The bundle version change (3.1.0 to 3.1.0) is too low, the new version must be at least 3.1.1
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] MicroProfile Health ................................ SUCCESS [01:02 min]
[INFO] MicroProfile Health API ............................ FAILURE [ 34.714 s]
[INFO] MicroProfile Health TCK ............................ SKIPPED
[INFO] MicroProfile Health Specification .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:01 min
[INFO] Finished at: 2022-01-12T10:23:05+00:00
[INFO] Final Memory: 52M/264M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal biz.aQute.bnd:bnd-baseline-maven-plugin:5.2.0:baseline (baseline) on project microprofile-health-api: An error occurred while calculating the baseline: The baselining plugin detected versioning errors

can you help @Emily-Jiang

**Comment by Emily-Jiang** [comment]
ok, I will take a look at it.

**Comment by Emily-Jiang** [comment]
@saumya1singh the current master is on 4.1-SNAPSHOT. Are you building any branch?

**Comment by Emily-Jiang** [comment]
I pushed the master and it built okay for me. Can you give me the reproduce?

**Comment by saumya1singh** [comment]
Hi I am not building master @Emily-Jiang

**Comment by saumya1singh** [comment]
https://github.com/eclipse/microprofile-health/tree/3.1 I am building 3.1 as needed for our project

**Comment by saumya1singh** [comment]
```
mvn clean deploy dependency:tree -DskipTests -Dasciidoctor.skip -Drat.skip=true
``` 
is the command I am using

**Comment by Emily-Jiang** [comment]
I am building 3.1 successfully. 
[INFO] Reactor Summary for MicroProfile Health 3.1:
[INFO] 
[INFO] MicroProfile Health ................................ SUCCESS [  1.569 s]
[INFO] MicroProfile Health API ............................ SUCCESS [  5.003 s]
[INFO] MicroProfile Health TCK ............................ SUCCESS [  2.930 s]
[INFO] MicroProfile Health Specification .................. SUCCESS [ 11.487 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21.123 s
[INFO] Finished at: 2022-01-13T11:52:05Z

Looks like you have made some changes on 3.1? If so, the error message told you what to do:

[ERROR] The bundle version change (3.1.0 to 3.1.0) is too low, the new version must be at least 3.1.1

Update the version from 3.1 to 3.1.1 or 3.2-SNAPSHOT in all of the pom.xml

**Comment by saumya1singh** [comment]
ok let me try that. 
thanks for the quick response!

**Comment by saumya1singh** [comment]
this can be closed. thanks
