### ISSUE TITLE
data field of type  Optional<Map<String, Object>> 

### ISSUE THREAD

**Issue by gquintana** [eclipse/microprofile-health#323]
Having a field of type  `Optional<Map<String, Object>>` does not make sense to me,
When no data has been set, returning a empty Map instead of an empty Optional is far simpler and clearer.
Wrapping a Collection in an Optional is not considered as a good practice:
* https://dzone.com/articles/is-it-worth-it-to-use-optional-in-collections
* https://justamonad.com/wrapping-collection-in-optional-is-a-big-no-no/

At least could you add helper methods like
```
    public Map<String, Object> getDataMap() {
        return getData().orElse(Collections.emptyMap());
    }
    public Optional<Object> getData(String key) {
       return getData().map(data -> data.get(key));
    }
```

**Comment by HerrDerb** [comment]
yes, we just ran into an unexpected NPE because of this. 
1. `Optional` as a field is a very bad smell. 
2. It is even worse if the field additionally get initialized with `null`.

This code should be refactored
