### ISSUE TITLE
Add example where Health procedures are produced instead of defined by bean class

### ISSUE THREAD

**Issue by heiko-braun** [eclipse/microprofile-health#36]
From @jmesnil 

We could also reuse the `@Health` annotation for CDI. Any no-arg operation annotated with `@Health` and returns a HealthStatus is a health check procedure (no need to introduce the HealthCheckProcedure for that). This has several advantages:
* the `@Health` annotation can be named (instead of the HealthStatus)
* If a global binding is chosen, we can check at CDI deployment that every health check procedures has an unique name
* a single class can provide several health check procedure:

```
class MyChecks {

  @Health("memory")
  HealthStatus call() {
    return HealthStatus.state(getMemUsage() < 90%);
  }

  @Health("cpu")
  HealthStatus call() {
    return HealthStatus.state(getCpuUsage() < 90%);
  }

}
```

**Comment by pilhuhn** [comment]
While the above example is obviously bad (2 methods with same name and signature), this should allow to not provide a name on the annotation, but rather take the method name by default. 
In Metrics we default to the FQCN.method_name. if an attribute of `absolute` is true, then only the method_name is taken. If an explicit name is given, this one is taken. See https://github.com/eclipse/microprofile-metrics/blob/master/spec/src/main/asciidoc/metrics_spec.adoc#fields

**Comment by mkouba** [comment]
If `HealthCheck` procedures were supposed to be bean instances you could have used:
```
class MyChecks {

  @Produces
  @Health("memory")
  HealthCheck check1() {
    return () -> return HealthStatus.state(getMemUsage() < 90%);
  }

  @Produces
  @Health
  HealthCheck check2() {
    return () -> HealthStatus.state(getCpuUsage() < 90%);
  }
}
```

**Comment by antoinesd** [comment]
I think @mkouba proposal should be retain and perhaps we could add an exemple of produced HealthCheck in the integration with CDI section

**Comment by antoinesd** [comment]
Health procedure are already CDI beans. IMO it's not useful to specify that we support produced Health procedures. But giving an examples with prodqcures produced is interesting.
