### ISSUE TITLE
Support for system level health check procedures

### ISSUE THREAD

**Issue by heiko-braun** [eclipse/microprofile-health#37]
From @jmesnil 

The server runtime could also provide some HealthCheckProcedure that are not application-dependent (e.g. JVM memory, disk space, CPU load). These procedures need to be accessed from a HTTP endpoint not provided by the application (e.g. /health)

**Comment by heiko-braun** [comment]
@jmesnil Are you willing to draft a design proposal how these procedures could be discovered/registered?

**Comment by antoinesd** [comment]
Relation with system should be considered in a broader scope and after 1.1 and introduction of #35

**Comment by antoinesd** [comment]
This issue is vendor specific and cannot be addressed at specification level
