### ISSUE TITLE
api @Health

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-health#4]
I looked at the api and the proposal. I am confused on how to use the api.

@GET
   @Path("/diskspace")
   @Health
   public HealthStatus checkDiskspace() {
       [...]
   }

what is the purpose of @Health? Will this expose an end point of /health? Why does this method has the return type of HealthStatus? 

I am even more confused with 
@Produces    
   @Health
   public HealthStatus checkDiskspace() {
       [...]
   }

Do you suggest @Health is just a qualifier? This is a producer. Do you suggest there is an injection somewhere to inject the HealthStatus?

Where do you imply /health end point was exposed?

**Comment by heiko-braun** [comment]
I'll write up some use cases and relate them to protocol spec. Then the API's become clearer. But as a starter I would suggest to skim through https://github.com/eclipse/microprofile-evolution-process/blob/master/proposals/0003-spec.md

**Comment by Emily-Jiang** [comment]
I have read the spec but it does not help with the questions above. Can you please provide a quick answer if you don't mind?

**Comment by heiko-braun** [comment]
So, `/health` returns a composite response of all health check procedures being installed into the runtime. The `@Health` annotated methods denote  these procedures and can either produced from CDI beans or without CDI simply through JAX-RS method implementations. But I am not sure if the later approach would still be needed and useful in the context of the microprofile, which always ships a CDI dependency.

**Comment by heiko-braun** [comment]
Regarding your second question: `HealthStatus` is the result type for health check procedures, that carries all the fields required by the wire format. i.e. id, status and optional key/value pairs for additional information.

**Comment by Emily-Jiang** [comment]
Thanks for your explanation! If you think JAX-RS method is not useful, why put in the spec? JAX-RS is always in the microprofile context as well though. Why do you need a CDI producer for HealthStatus since it is not injected anywhere. I cannot see any meaningful contribution from CDI though. What do you need CDI for? I feel this needs a bit more thoughts. 

Do you suggest once the annotation @Health is present, your application will expose an end point /health? What if you have multiple @Health, do you aggregate the health status?

**Comment by heiko-braun** [comment]
This all just pseudo code at the moment. At present (in Swarm) we only support the JAX-RS approach. The other CDI examples are merely food for thought.

**Comment by heiko-braun** [comment]
@Emily-Jiang Let's focus on the CDI based approach using real code (see https://github.com/eclipse/microprofile-health/pull/7). I am tempted to drop the JAX-RS bindings: https://groups.google.com/forum/#!topic/microprofile/IbB2TziPWLU . For now I am closing this issue.
