### ISSUE TITLE
Revisit API terms

### ISSUE THREAD

**Issue by jmesnil** [eclipse/microprofile-health#43]
This issue is to keep track of remarks made by @Emily-Jiang in https://github.com/eclipse/microprofile-health/pull/32#discussion_r126624736 about API names.

In general, I think we should aim to have consistent names across MicroProfile specifications for similar concepts (Builder, Service Loader Resolver, etc.)

**Comment by heiko-braun** [comment]
When we touch this, we should also fix #40
