### ISSUE TITLE
Cater for OSGi Environments

### ISSUE THREAD

**Issue by Pandrex247** [eclipse/microprofile-health#44]
Following on from a comment made by Emily Jiang in PR #32 about an issue from the Config API project, will this not need a similar `setInstance(SPIFactory spiFactory)` method for this to work in an OSGi environment?

**Comment by heiko-braun** [comment]
Probably yes, but I am not experienced with OSGI runtimes. Would you like to provide a PR for this?

**Comment by starksm64** [comment]
Resolved with #46
