### ISSUE TITLE
What security should be required for the /health endpoint?

### ISSUE THREAD

**Issue by rlcundiff** [eclipse/microprofile-health#47]
In the security section of  the document it says
HTTP Digest Auth MUST be one supported authentication mechanism
HTTP Digest Auth SHOULD be the default algorithm for the HTTP protocol binding

HTTP digest auth is optional for JEE so why would want to require it here?  Instead, since JWT will be included in Microprofile 1.2 shouldn't we require using JWT?  It seems it would be no extra effort to do so.

Also, since both CDI and JWT are both present, a HealthCheck implementation should be able to inject @Principal and @JsonWebToken.  Wouldn't we want to declare this in the spec?

**Comment by starksm64** [comment]
If an MP-JWT implementation co-exists with an MP-HEALTH implementation, it would be automatic that one can inject the MP-JWT principal and token claims. It could be referenced from the HealthCheck spec, but I don't see that there is anything to declare.

In terms of requiring MP-JWT auth for the HealthCheck endpoints, I can see that this would be potentially be more difficult than supporting Digest Auth as MP-JWT is a custom authentication scheme not even mentioned by the servlet spec, while Digest Auth is mentioned as something that should be supported.

And, even if it is supported by the underlying container, it may be an issue to configure the HealthCheck clients to support obtaining a bearer token. 

While we should define interop of the MP features, I think we want to keep the 1.0 release rather simple and build up requirements as we go.

**Comment by kwsutter** [comment]
So, what do you suggest, Scott?  That we remove all authentication
requirements for the /health endpoint in this first release?  Seems to
leave this quite open...  Do you think not specifying any authentication is
sufficient?  And, leave it to an "implementation detail"?

Since both JWT and HealthCheck are proposed for MP 1.2, then specifying a
dependency on JWT might be okay.  Kind of like our previous dependencies on
CDI.

Following up on some of your comments, do you see HealthCheck being used
outside of MicroProfile and that's why you don't want to have the
dependency on JWT?

Thanks, Kevin

**Comment by heiko-braun** [comment]
I agree with Scott:

> While we should define interop of the MP features, I think we want to keep the 1.0 release rather simple and build up requirements as we go.

The specs  should be interopable yes, but I am against hard dependencies (i.e. making JWT auth a mandatory element in the health spec). That said and in response to @kwsutter 's concern

> we remove all authentication
requirements for the /health endpoint in this first release?  Seems to
leave this quite open... 

Some authentication mechanism would be good to enforce in 1.0 and digest is the mandatory requirement in the current spec. The JEE argument brought forward by @rlcundiff is less of a concerns to me. Even if it's optional in JEE, I think basically all HTTP server implementations support it. Digest strikes a good balance between out-of-the-box experience (think setup and configuration) and actual security. 

## Payload constraints

An alternative to actual authentication in 1.0 could be working around payload constraints. Think of it: authentication is really just required if something vulnerable or secret is exposed. IMO this is the response payload of `HealthCheck` procedures. Hence I believe an alternative, much more simple approach to bypass authentication needs would be toggles that suppress the response payload, i.e.:

```
**@Health(sensitive=true)**
@ApplicationScoped
public class SecuredCheck implements HealthCheck {

    public Response call() {
        return Response.named("successful-check").up();
    }
}
```

In the above pseudo code example (we don't yet have the `@Health` annotation), the usage of `@Health(sensitive=true)` indicates that the response payload will be suppressed and only the outermost protocol status codes (i.e. `503` and `200` used to signal the system state).

## Some general thoughts on security

If you think on a whole-system level (i.e. including the health consumers) then authentication becomes quite a different twist. The spec says health checks are primarily intended to be used for machine-to-machine communication and could be used by human operators, but that's a secondary concern. 

I believe the typical cloud platform use cases is machine-to-machine and significantly constraints the ability to introduce authentication on this level of interaction. For instance I don't know of any cloud platform that leverages health checks that actually supports authentication (someone please correct me here).

From this point of view authentication really just addresses the use cases that the spec currently declares as secondary concerns (usage by human operators).

**Comment by starksm64** [comment]
@kwsutter, no, the concern is not HeathCheck is used outside of MP environments, the concern is what @heiko-braun brings up with the point that the most common user of the health check are containerized/cloud environments where there is some question as to whether a custom bearer token auth mechanism like JWT could be easily introduced.

What I would propose is that we say security SHOULD be supported the the /heath endpoint, and that DIGEST and MP-JWT SHOULD be supported, but not go beyond that. As @heiko-braun mentions, I expect that most cloud environments will be using the trusted domain feature to bypass a security check altogether.

**Comment by starksm64** [comment]
So what is the feeling about updating the security section of the HC spec to the following:

- A producer MUST enforce security on all health check invocations if the context associated with the endpoint has been configured as secure.
- A producer MAY ignore security for trusted origins (e.g., localhost)
- HTTP Digest Auth SHOULD be one supported authentication mechanism.
- MP-JWT Auth SHOULD be one supported authentication mechanism.

**Comment by johnament** [comment]
IMHO, we should not go this route.  [Environments like AWS](http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-healthchecks.html#health-check-configuration) explicitly do not support authentication.  So this would be a show stopper for me.   If we want to make security an option, that is fine.  But I would avoid the issue fault tolerance and just say that by default no authentication, however you can configure authentication via some means, possibly via the MP Config API.

**Comment by heiko-braun** [comment]
@johnament We thought of an alternative with the following characteristics:

- All response payload would be suppressed by default for non-authenticated requests
- This removes the need for authentication all together as we would not be exposing sensitive data to un-authenticated requests
- Meta data (i.e. `@Health(sensitive=false)`) could be used to override the default behaviour per health check

Does this sounds like a reasonable balance between out-of-the-box experience and security needs?

**Comment by johnament** [comment]
Sure, but I'm assuming for v1 you're only going to mention the first bullet?

**Comment by heiko-braun** [comment]
I think we can do all three bullets. The annotation is alteady there

**Comment by johnament** [comment]
I would be against bullet 3 in the current form.  If I'm providing a library that enables health out of the box, I wouldn't want my library to determine whether or not a check is considered sensitive.

bullet 2 isn't a spec item.

**Comment by heiko-braun** [comment]
@starksm64 @johnament Let's move this to 1.1 It requires further thought.

**Comment by heiko-braun** [comment]
I would suggest the following for 1.0:

Change the spec to recommend auth protocols, rather than requiring them and making it explict that neither of this is enforced, but up to the implementation.

All of this require much further thought, especially considering that practically no cloud platforms support auth with health checks

**Comment by heiko-braun** [comment]
@rlcundiff I'll leave this open and created #98 for 1.0

**Comment by ebullient** [comment]
For reference, Spring supports authentication for the health check endpoints generated by their actuators. As noted, it acts as a filter on the returned payload (it has no bearing on which checks are executed). Unauthenticated requests get the sparest of answers `{"status":"UP"}` or `{"status":"DOWN"}`. You only get the details if you're logged in. To me, that is the difference between use by automation (up/down) and use by a human (what exactly is going on with this server...).

**Comment by heiko-braun** [comment]
Thanks @ebullient , that works for me too. Either no payload at all for un-authenticated requests or just the `status` attribute, but maybe along with the `name` of the check.

**Comment by heiko-braun** [comment]
I am closing this (question) as resolved. It seems we know how we want to address this problem and moving forward wi'll use  #2 to track progress. I will carry over the relevant parts to #2
