### ISSUE TITLE
Support for CDI beans that implement HealthCheck as health check procedures

### ISSUE THREAD

**Issue by heiko-braun** [eclipse/microprofile-health#49]
The most simple CDI use case would be to discover beans that implement `HealthCheck`, i.e.:

```
public class SuccessfulCheck implements HealthCheck {
    @Override
    public Response call() {
        return Response.named("successful-check").up();
    }
}
```

**Comment by heiko-braun** [comment]
I've created this issue to distinguish the simple use case, from the approach described in #36

**Comment by heiko-braun** [comment]
#52 acts a baseline to verify the bare bone CDI integration works

**Comment by johnament** [comment]
I'm having a hard time understanding the goal of this ticket.  Update the spec? The TCK? The API?  From what I can tell in each of the TCK tests you're already expecting health checks to be discovered as CDI beans.

**Comment by heiko-braun** [comment]
@johnament yes, but there was some uncertainty in the community if CDI is included or not. This ticket makes it explicit.

**Comment by heiko-braun** [comment]
With #52 being merged this can be closed
