### ISSUE TITLE
Need 3rd party clearance for dependencies

### ISSUE THREAD

**Issue by kwsutter** [eclipse/microprofile-health#5]
Per the Initial Contribution Questionnaire process, we need to file Contribution Questionnaires for all of the 3rd party software that we are dependent on.
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12628

The Process is documented here:
https://www.eclipse.org/projects/handbook/#ip-third-party

I grepped the pom.xml files for this component and found the following dependencies... We will need to get these filed before we could release health-1.0.

Also, some (but not all) of these dependencies may be resolved via the related Config Issue:
https://github.com/eclipse/microprofile-config/issues/170

````
Dependencies covered by config? -- not all
<dependency>
    <groupId>javax.enterprise</groupId>
    <artifactId>cdi-api</artifactId>
    <version>1.2</version>
</dependency>
<dependency>
    <groupId>org.jboss.arquillian</groupId>
    <artifactId>arquillian-bom</artifactId>
    <version>1.1.12.Final</version>
    <scope>import</scope>
    <type>pom</type>
</dependency>

<dependency>
    <groupId>org.wildfly.swarm</groupId>
    <artifactId>bom-all</artifactId>
    <version>${wildfly-swarm.version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
<dependency>
    <groupId>org.wildfly.swarm</groupId>
    <artifactId>jaxrs</artifactId>
</dependency>

<dependency>
    <groupId>org.wildfly.swarm</groupId>
    <artifactId>monitor</artifactId>
</dependency>

<dependency>
    <groupId>org.eclipse.microprofile.health.tck</groupId>
    <artifactId>microprofile-health-tck</artifactId>
    <version>1.0-SNAPSHOT</version>
    <scope>test</scope>
</dependency>

<dependency>
    <groupId>org.wildfly.swarm</groupId>
    <artifactId>arquillian</artifactId>
    <scope>test</scope>
</dependency>

<dependency>
    <groupId>org.jboss.arquillian.junit</groupId>
    <artifactId>arquillian-junit-container</artifactId>
    <scope>test</scope>
</dependency>
<dependency>  -- why not use javax jaxrs 2.0 standard instead of jboss?
    <groupId>org.jboss.spec.javax.ws.rs</groupId>
    <artifactId>jboss-jaxrs-api_2.0_spec</artifactId>
    <version>1.0.0.Final</version>
    <scope>provided</scope>
</dependency>

<dependency>
    <groupId>org.jboss.arquillian.junit</groupId>
    <artifactId>arquillian-junit-container</artifactId>
</dependency>

<dependency>
    <groupId>org.jboss.arquillian.container</groupId>
    <artifactId>arquillian-container-test-spi</artifactId>
</dependency>

<dependency>
     <groupId>junit</groupId>
     <artifactId>junit</artifactId>
     <scope>compile</scope>
    <version>${junit.version}</version>
</dependency>

<dependency>
    <groupId>org.jboss.shrinkwrap</groupId>
    <artifactId>shrinkwrap-api</artifactId>
    <scope>compile</scope>
</dependency>

<dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpclient</artifactId>
    <version>4.5.2</version>
    <scope>compile</scope>
</dependency>

<dependency>
    <groupId>commons-logging</groupId>
    <artifactId>commons-logging</artifactId>
    <version>1.2</version>
    <scope>test</scope>
</dependency>
````

**Comment by keilw** [comment]
Not sure about Arquillian, but JUnit and commons-logging should be approved via Orbit. If we need a more recent version than the one that's approved, a CQ is also necessary for the update, but that should work faster than for a newly added library.

**Comment by heiko-braun** [comment]
From @kwsutter 

> If we're going to update a dependency (Swarm) version, then please open the corresponding Contribution Questionnaire. Reference Issue #5 for some details, and my discussion on our Google Group: https://groups.google.com/forum/#!topic/microprofile/CSP0rPutSGw

**Comment by heiko-braun** [comment]
Let's wait until things settle a bit. The whole API still still in flux.

**Comment by keilw** [comment]
I noticed, it's JUnit here and TestNG in other cases like Config. 
Couldn't there be a consensus on a single tool for MP, also making IP vetting easier?

**Comment by heiko-braun** [comment]
I am all for consolidation of shared libs. How should we drive this? Creating a thread on the mailing list for shared components?

**Comment by keilw** [comment]
Would be a start. Ideally an "Inbound BOM" for those kinds of things would be good. Different from the "Outbound BOM" only containing API dependendies.

**Comment by kwsutter** [comment]
I'm finding that getting IP review of the build and test dependencies is
not as bad as originally thought...  I haven't gotten final approval yet,
so maybe I'll have to eat those words.  But, let's not spend a lot of time
trying to come up with a list of shared components.  For one thing, we
don't necessarily want all of the individual components to be tightly
integrated, even if it's just from a build and test perspective.

**Comment by kwsutter** [comment]
With a couple of minor dependency version updates, I think microprofile-health looks good for the initial IP scanning...  PR coming soon.

**Comment by kwsutter** [comment]
All associated CQs are now complete.  Will need to re-submit CQs for any updates to our dependencies (runtime or build/test).
