### ISSUE TITLE
Add an example with two checks

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-health#54]
The spec needs some clean up.  There are only examples right now with single checks, which imply that you would only have one check available.  We should have examples with multiple checks, as well as give an example of one check passing and one check failing.

**Comment by heiko-braun** [comment]
@johnament The TCL already contains an example of the scenario you describe: 
https://github.com/eclipse/microprofile-health/blob/master/tck/src/main/java/org/eclipse/microprofile/health/tck/MultipleProceduresFailedTest.java

What else do you think needs to be done?

**Comment by heiko-braun** [comment]
@johnament ?

**Comment by johnament** [comment]
I'm specifically talking about [this section](https://github.com/eclipse/microprofile-health/blob/master/spec/src/main/asciidoc/protocol-wireformat.adoc#with-procedures-installed-into-the-runtime) which only mentions a single check.  I get we have TCK for this, but would be good to explain the spec what's expected (e.g. that 1 failing check makes the entire check failed)

**Comment by heiko-braun** [comment]
Moving to #55
