### ISSUE TITLE
Clean up spec

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-health#55]
https://github.com/eclipse/microprofile-health/tree/master/spec/src/main/asciidoc

Still includes config as a spec file.

**Comment by heiko-braun** [comment]
@johnament good catch. I'd say we'll revisit this when the once the remaining issues are resolved.

**Comment by heiko-braun** [comment]
@johnament I wonder if this doc is actually required. We currently have

a) the README
b) the companion doc that describes the protocol

Do you think anything else would be needed for 1.0?

**Comment by johnament** [comment]
its whatever should be generating the spec in my opinion.

**Comment by starksm64** [comment]
I have cleaned up most of this as part of the changes I made for #67 
We do need some general architecture overview to address things in the protocol doc that are a little terse. I'll do that since I'm learning the definitions.

**Comment by heiko-braun** [comment]
I'll flesh out some diagrams over the weekend and go over the documentation.

**Comment by johnament** [comment]
While you're in there, can you Rational -> Rationale ?

**Comment by heiko-braun** [comment]
Requested by @johnament 

> Add an example with two health procedures. I'm specifically talking about this section which only mentions a single check. I get we have TCK for this, but would be good to explain the spec what's expected (e.g. that 1 failing check makes the entire check failed)
