### ISSUE TITLE
Revisit how HealthCheckResponseProvider works

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-health#58]
The way SPIFactory is defined is a bit confusing.  Health checks only apply while the container is running, unlike Config which has a state before the entire container is online.  It seems more appropriate to me that SPIFactory's role is replaced by a CDI bean that can create ResponseBuilder's rather than service loader.

**Comment by heiko-braun** [comment]
I don't think we should make the SPI dependent on CDI. Although CDI is a first class programming model, both API and SPI should be designed to be used in runtime that don't support CDI.

**Comment by johnament** [comment]
Hi,

Well, I think I found a bug in how the SPI works.

In `Response.named`, if the factory is already set you just return that, instead of returning with the proper name (like done at the end of the method).

However, I think it would be good if the factory supported look up via CDI, instead of expecting a service loader.  

FWIW, In Hammock, I'm going to support the following:

```java
@Dependent
public class MyCheck implements HealthCheck {
   @Inject ResponseBuilder responseBuilder;

   public Response call() {
     return responseBuilder.up();
   }
}
```

Where name is derived from the check and user can just work with this option.  So from my POV the service loader introduces a weird complexity.

**Comment by antoinesd** [comment]
Removing from 1.1 but should considered again in the future

**Comment by antoinesd** [comment]
Out of date
