### ISSUE TITLE
Add a built in literal for `@Health`?

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-health#74]
It would be really useful if we had a built in literal for `@Health`.  Makes programmatic look up easier.

**Comment by heiko-braun** [comment]
What do you mean with "literal"?

**Comment by johnament** [comment]
In Java, you can't instantiate an annotation.  However, CDI introduces the notion of an [AnnotationLiteral](https://docs.jboss.org/cdi/api/1.0/javax/enterprise/util/AnnotationLiteral.html) which lets you do just that.  Its extremely useful for programmatic look up, for instance Hammock uses one [HealthLiteral](https://github.com/hammock-project/hammock/blob/master/util-health/src/main/java/ws/ament/hammock/health/HealthLiteral.java) to handle finding [health checks that are available](https://github.com/hammock-project/hammock/blob/master/util-health/src/main/java/ws/ament/hammock/health/HealthCheckManager.java#L48).

In the CDI EG, we learned that providing built in literals for the spec provided qualifiers makes a lot of sense.  I suspect it'll make a lot of sense here as well.

**Comment by heiko-braun** [comment]
Sure, can provide a PR? That would help to see how this might be leveraged.

**Comment by mkouba** [comment]
OT: What is the `@Health` qualifier for? The `HealthCheck` type should be enough for typesafe resolution.

**Comment by antoinesd** [comment]
Yes, good question @mkouba. It seems to be redundant. How the impl should behave if you annotated with `@Health` a class that doesn't implement `HealthCheck` ?

**Comment by pilhuhn** [comment]
I can imagine that `@Health` makes it very easy to find the respective class from the deployment processor, as the annotations can easily be found in the Jandex index.

Personally I would keep `@Health' , but not require the interface. There is https://github.com/eclipse/microprofile-health/issues/36 about this.

**Comment by johnament** [comment]
@mkouba that question came up when it was originally introduced.  I'm not sure why it benefits an internal JBoss tool or if dependency on an internal JBoss tool should make its way into the spec, but I personally don't see any benefit to the qualifier.  In fact, the default behavior within Hammock is that this qualifier is not used

https://github.com/hammock-project/hammock/blob/master/util-health/src/main/java/ws/ament/hammock/health/HealthCheckManager.java#L39-L57

**Comment by mkouba** [comment]
@pilhuhn Hm, the question is whether you need to inspect the deployment like this. I found a similar approach much easier:

```
class MyChecks {
  @Inject
  Instance<HealthCheck> checks;

  void perform() {
    checks.forEach(check -> check.call()); // check the response
  }
}
```
Also I wouldn't get rid of the `HealthCheck` contract - again, it's much easier to use (no reflection needed etc.).

**Comment by mkouba** [comment]
@johnament Yeah, I checked the hammock impl yesterday ;-)

**Comment by heiko-braun** [comment]
HealthChecks are really just bindings to the protocol layer.  As such the above example ` @Inject
  Instance<HealthCheck> checks;` doesn't make much sense to me. That said, if the majority of contributor believes this is needed, then clearly layout your proposed changes with use cases and code samples and ask for a vote.

**Comment by heiko-braun** [comment]
@mkouba @johnament I think clarification of the CDI usage this sounds like a good aim for 1.1, Would you be interested to drive that release and the related spec changes?

**Comment by antoinesd** [comment]
In ticket #119 we decided to deprecate `@Health` qualifier so Literal is not needed anymore: I close the ticket
