### ISSUE TITLE
Using an already located factory causes the name to be ignored.

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-health#78]
There's a bug in the API, where if the factory has already been set, the API ignores the name and just creates a new response builder.  Instead, that builder should have a name.

**Comment by johnament** [comment]
Reopening, this commit is missing for unknown reasons now.

**Comment by heiko-braun** [comment]
@johnament is it? See https://github.com/eclipse/microprofile-health/blob/master/api/src/main/java/org/eclipse/microprofile/health/HealthCheckResponse.java#L64

**Comment by heiko-braun** [comment]
I've rolled back the other commit, which made this one disappear, but apparently the changes to fix the bug are included, no?
