### ISSUE TITLE
Separate the JSON bindings from the actual API classes

### ISSUE THREAD

**Issue by heiko-braun** [eclipse/microprofile-health#8]
The current API is based on an implementation in another project. Here the separation of concerns wasn't relevant, but in the MP the API should be decoupled from the wireformat (json)

**Comment by heiko-braun** [comment]
Maybe we should fully delegate this to the implementation?

**Comment by keilw** [comment]
Then a `toJson()` method in the API sounds biased. Wouldn't simply declaring `toString()` in the interface be better in such case? Leaving it to implementations if they use JSON, XML or something else.

**Comment by heiko-braun** [comment]
I think we should remove `toJson()` all together and simply impose the need for a JSON encoded wireformat. But that doesn't need to be reflected in the API at all.
