### ISSUE TITLE
Unnecessary duplicate arquillian import

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-health#87]
https://github.com/eclipse/microprofile-health/blob/master/pom.xml#L71
https://github.com/eclipse/microprofile-health/blob/master/tck/pom.xml#L40

We should only have one, and I would recommend only putting it in the tck since that's the only area where Arquillian is used.

**Comment by Pandrex247** [comment]
Arquillian is also used in the sample implementation, but I agree it would be cleaner to just have one.
