### ISSUE TITLE
Running the TCK needs to be updated

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-health#91]
https://github.com/eclipse/microprofile-health/blob/master/tck/running_the_tck.asciidoc

#82 was merged before it was ready (which is why I'm guessing you did #89).  The docs still need to be updated to reflect that the system property is no longer required, and they should instead be providing an Arquillian URI resource provider.

**Comment by heiko-braun** [comment]
And the TCK section needs to be linked from the spec doc I guess
